FIR_Generator/FIR_Generator/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landingPage, name="landingPage"),
    path('user', include("user.urls", namespace="user")),
    path('sho', include("sho.urls", namespace="sho")),
    path('controller', include("controller.urls", namespace="controller")),
]       

FIR_Generator/sho/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "sho"
urlpatterns = [
    path('/', views.loginregister, name="shoLoginregister"),
    path('/home/<slug:slug>', views.homeSHO, name="shoHome"),

    path('/login', views.loginSHO, name="shoLogin"),
    path('/logout', views.logoutSHO, name="shoLogout"),

    path('/pending/<slug:slug>', views.pendingFIR, name="pendingFIR"),
    path('/fir/<slug:slug>', views.viewPendingFIR, name="viewPendingFIR"),
    path('/fir/approve/<slug:slug>', views.approvePendingFIR, name="approvePendingFIR"),
    path('/fir/solved/<slug:slug>', views.markSolvedFIR, name="markSolvedFIR"),



    path('/approved/<slug:slug>', views.approvedFIR, name="approvedFIR"),

    path('/searchFIR', views.searchFIR, name="searchFIR"),

    path('/solved/<slug:slug>', views.solvedFIR, name="solvedFIR"),
    

]

FIR_Generator/sho/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


    

FIR_Generator/sho/views.py
from django.shortcuts import render, redirect, HttpResponse,get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from user.models import FIR
from datetime import datetime

# Create your views here.
def loginregister(request):
    return render(request, "sho/loginregistration.html")

def homeSHO(request,slug):
    user = get_object_or_404(User, username = slug)
    station = user.first_name
    pincode = user.last_name
    context = { 'station':station, 'pincode': pincode}
    return render(request, 'sho/landing.html', context)

def loginSHO(request):

    if request.method == "POST":

        email = request.POST['email']
        loginpassword = request.POST['password']
        try:
            UserData = get_object_or_404(User, email = email)
        except:
        
            print('sho')
            messages.error(request, "Invalid Credentials given, Please check and retry again")
            
            return redirect('sho:shoLoginregister') 
        username = UserData.username 
            

        user = authenticate(username = username, password = loginpassword)
        
        if user is None:
            messages.error(request, "Invalid Credentials, Please check and retry again")
            
            return redirect('sho:shoLoginregister')         
        else:
            login(request,user)
            station = user.first_name
            pincode = user.last_name
            
            messages.success(request, "Successfully Logged In")
            context = {'user':username,'email':email, 'station':station, 'pincode': pincode}
            
          
            return render(request,'sho/landing.html', context)
    else:
        return redirect('sho:shoLoginregister')
    
 
def logoutSHO(request):
    logout(request)
    messages.success(request, "Successfully Logout")
    return redirect('/')

def pendingFIR(request,slug):
    pendingFIR = FIR.objects.filter(pincode = slug,status = False, solved = False)
    report = 'Pending'
    context = {'pendingfir':pendingFIR, 'report':report}
    
    return render(request, 'sho/pendingfir.html', context)

def viewPendingFIR(request, slug):
    userfir = get_object_or_404(FIR, sno = int(slug))

    context = {'userfir':userfir}
    return render(request, 'sho/viewfir.html', context)
    
def approvePendingFIR(request, slug):
    userfir = get_object_or_404(FIR, sno = int(slug))
    pincode = userfir.pincode
    userfir.status = True
    userfir.save()
    messages.success(request, "Successfully Approved Pending FIR")
    pendingFIR = FIR.objects.filter(pincode = pincode, status = False)
    context = {'pendingfir':pendingFIR}
    return render(request, 'sho/pendingfir.html', context)

def markSolvedFIR(request, slug):
    userfir = get_object_or_404(FIR, sno = int(slug))
    pincode = userfir.pincode
    userfir.solved = True
    
    userfir.save()
    messages.success(request, "Successfully Mark Solved to Approved FIR")
    pendingFIR = FIR.objects.filter(pincode = pincode, status = True,solved=False)
    context = {'pendingfir':pendingFIR}
    return render(request, 'sho/pendingfir.html', context)


def approvedFIR(request, slug):
    approvedFIR = FIR.objects.filter(pincode = slug,status = True, solved=False)
    report = 'Approved'
    context = {'pendingfir':approvedFIR, 'report':report}
    return render(request, 'sho/pendingfir.html', context)

def searchFIR(request):
    
    return render(request, 'sho/search.html')

def solvedFIR(request, slug):
    solvedFIR = FIR.objects.filter(pincode = slug,solved=True)
    report = 'Solved'
    context = {'pendingfir':solvedFIR, 'report':report}
    return render(request, 'sho/pendingfir.html', context)
    

FIR_Generator/templates/sho/landing.html
{% extends 'header.html' %}
{% load static %}
{% block navimg %}
<img src="{% static 'sho_avt.png' %}" alt="Person" width="96" height="96">
{% endblock navimg %}

{% block bodyStyle %}style="height: 100vh;justify-content: start;"{% endblock bodyStyle %}


{% block body %}

<hr>
<div>

    <div class="container mt-5">
        <div class="row">
            <div class="col-sm-2">
                <img class="img-responsive pt-2" style="width: 10em; height: 6em;"
                    src="{% static 'main/firgenlogo.jpg' %}" alt="No" />
            </div>
            <div class="col-sm-1 vl"></div>
            <div class="col-sm-9 head">
                <h4 class="fm2">ONLINE FIR GENERATOR</h4>
                <p>Department Of Complaint</p>
            </div>
        </div>
    </div>

    <hr class="mt-0 mb-1" />
    <nav class="navbar navbar-expand-lg navbar-light sec-nav" style="background-color: #f3e3ae96;">
        <a class="nav-link" href="#">About Us</a>
        <!-- <a class="nav-link" href="/my">My Dashboard</a> -->
        <!-- <a class="nav-link" href="#">Downloads</a> -->
        <a class="nav-link" href="#">Help</a>
        <a class="nav-link" href="#">Frequently Asked Questions</a>
        <a class="nav-link" href="#">Contact & Support</a>
    </nav>
    <br />
    <div class="container sv">
        <h2 style="text-align: center;" class="fm2">Welcome to the SHO Page of {{station}}-{{pincode}}</h2>
        <div class="row">
            <div class="col-sm-6 d-grid gap-2">
                <a class=" btn btn-outline-dark btn-lg btn-block fm" href="/sho/pending/{{pincode}}">Pending FIR</a>
            </div>
            <div class="col-sm-6 d-grid gap-2">
                <a class=" btn btn-outline-dark btn-lg btn-block fm" href="/sho/approved/{{pincode}}">Approved FIR</a>

            </div>
        </div>
        <div class=" row">
            <div class="col-sm-6 d-grid gap-2">
                <a class="btn btn-outline-dark btn-lg btn-block fm" href="/sho/searchFIR">Search FIR</a>
            </div>
            <div class="col-sm-6 d-grid gap-2">
                <a class="btn btn-outline-dark btn-lg btn-block fm" href="/sho/solved/{{pincode}}">Solved FIR</a>
            </div>
        </div>
    </div>
</div>

</div>



{% endblock body %}

FIR_Generator/templates/sho/loginregistration.html
{% extends 'footer.html' %}

{% load static %}

{% block nav_content %}

<div style="justify-content: space-around;display: flex;">
  <a class="btn btn-dark  ml-2" style=" height: 100%; " href="/"> Back </a>
</div>

{% endblock nav_content %}

{% block body %}




  <div class="container login" id="container">
    
    <div class="form-container sign-in-container">

      <form action="{% url 'sho:shoLogin' %}" method="POST"> {% csrf_token %}
        <h1>Sign in</h1>
        <div class="social-container">
          <a href="#" class="social"><i class="fa fa-facebook"></i></a>
          <a href="#" class="social"><i class="fa fa-google"></i></a>
          <a href="#" class="social"><i class="fa fa-linkedin"></i></a>
        </div>
        <span>or use your account</span>
        <input type="email" placeholder="Email" name="email" />
        <input type="password" placeholder="Password" name="password" />
        <a href="#">Forgot your password?</a>
        <button>Sign In</button>
      </form>
    </div>
    <div class="overlay-container">
      <div class="overlay">
        
        <div class="overlay-panel overlay-right">
          <h1>New SHO ?</h1>
          <p>Contact Admin to register Yourself</p> 

        </div>
      </div>
    </div>
  </div>
  
  <script src="{% static 'loginregister/loginregister.js' %}"></script>
  {% endblock body %}

FIR_Generator/templates/sho/pendingfir.html
{% extends 'header.html' %}
{% load static %}
{% load humanize %}
{% block navimg %}
<img src="{% static 'sho_avt.png' %}" alt="Person" width="96" height="96">
{% endblock navimg %}

{% block bodyStyle %} style="height: {{style}}vh;  overflow-x: hidden;" {% endblock bodyStyle %}
{% block body %}


<br><br>
<div class="container mt-5">
    <a href="/sho/home/{{request.user}}" class="btn btn-primary"> HOME </a>
  </div>
  
  <h1 class="text-center fm2 ">{{report}} FIR Reports</h1>
  
  <div class="row text-center justify-content-center" style="display: grid; grid-template-columns: repeat(auto-fit, minmax(18rem, 1fr)); justify-items: center; align-items: center; gap: 20px;">
    {% for fir in pendingfir %}
    <div class="card shadow-lg  mb-5 bg-body rounded" style="width: 18rem;">
      <div class="card-body shadow-lg my-2">
        <h5 class="card-title fm2">Application No. : <span class="bg-danger">{{fir.sno}}</span></h5>
        <p class="card-text">Details: {{fir.typeofcrime}}</p>
      <hr>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Complaint Date: {{fir.timestamp | naturaltime}}</li>
        <li class="list-group-item">Crime Date: {{fir.incidentdatetime}}</li>
      </ul>
      <div class="card-body">
          {% if fir.solved %}
          <h3><span class="badge bg-success" >Solved</span></h3>
        {% elif fir.status %}
        <h3><span class="badge bg-info" >Approved</span></h3>
        
        {% else %}
        <h3><span class="badge bg-warning" >Pending</span></h3>

        {% endif %}
        
        <a href="/sho/fir/{{fir.sno}}" class="btn btn-primary btn-block">View/Download Complaint</a>
      </div>
    </div>
    </div>
    {% endfor %}
  </div>
  

  {% endblock body %}

  

FIR_Generator/templates/sho/search.html
{% extends 'header.html' %}
{% load static %}
{% load humanize %}
{% block navimg %}
<img src="{% static 'user_avt.png' %}" alt="Person" width="96" height="96">
{% endblock navimg %}

{% block bodyStyle %} style="height: 100vh;justify-content: start" {% endblock bodyStyle %}
{% block body %}

<style>
  .checkbox {
    transform: scale(1.5);
    margin-right: 10px;
  }
</style>

<div class="container mt-5">
    <a href="/user/home" class="btn btn-primary"> HOME </a>
  </div>
  
  <div class="container" >
    <h1 style="text-align: center;" class="fm2">Search FIR's Between Dates</h1>
    <br />
    <center>
    <form action="{% url 'user:searchFIR' %}" method="POST" > {% csrf_token %}
      <div class="form-row" style="justify-content: start;">  
        <div class="form-group col-md-6">
          <label for="fromdate">From Date</label>
          <input
            type="date"
            class="form-control mb-2 mr-sm-2"
            id="fromdate"
            name="date[from]"
            required
          />
        </div>
      </div>
  
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="todate">To Date</label>
          <input
            type="date"
            class="form-control mb-2 mr-sm-2"
            id="todate"
            name="date[to]"
            required
          />
        </div>
      </div>
      <input type="hidden" name="username" value="{{request.user}}">
      <label class="m-1">
        <input type="radio" name="status" value="All" class="checkbox">
        All
      </label>
      <label class="m-1">
        <input type="radio" name="status" value="pending" class="checkbox">
        Pending
      </label>
    
      <label class="m-1">
        <input type="radio" name="status" value="approved" class="checkbox">
        Approved
      </label>
    
      <label class="m-1">
        <input type="radio" name="status" value="solved" class="checkbox">
        Solved
      </label >
      
      <button type="submit" class="btn btn-primary mb-2">Search</button>
    </form>
  </center>
  </div>

  <h1 class="text-center mb-2 fm2">Searched Results</h1>
  <!-- style="display: grid; grid-template-columns: repeat(auto-fit, minmax(18rem, 1fr)); justify-items: center; align-items: center; gap: 20px;" -->
  <div class="row text-center  row row-cols-1 row-cols-sm-2 row-cols-lg-4 g-4 m-4">
    {% for fir in userfir %}
    <div class="col border border-dark border-1 rounded-3  shadow-lg p-3 mb-5 bg-body rounded">
      <div class=" card shadow-lg ">
        <div class="card-body">
          <h5 class="card-title ">Application No. : <mark class="bg-danger">{{fir.sno}}</mark></h5>
          <p class="card-text">Details: {{fir.typeofcrime}}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Complaint Date: {{fir.timestamp | naturaltime}}</li>
          <li class="list-group-item">Crime Date: {{fir.incidentdatetime}}</li>
        </ul>
        <div class="card-body">
          {% if fir.solved %}
          <span class="badge bg-success  fs-5  text-wrap">Marked Solved by SHO, {{fir.district}} </span>
          {% elif fir.status %}


          <span class="badge bg-success  fs-5  text-wrap">Digitally Verified by SHO</span>

          {% else %}
          <span class="badge bg-warning  fs-5 text-wrap">Pending</span>
          {% endif %}
          <hr>
          <a href="/user/fir/{{fir.sno}}" class="btn btn-primary btn-block">View/Download Complaint</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  {% endblock body %}
  

FIR_Generator/templates/sho/viewfir.html
{% extends 'header.html' %}
{% load static %}
{% load humanize %}
{% block navimg %}
<img src="{% static 'sho_avt.png' %}" alt="Person" width="96" height="96">
{% endblock navimg %}
{% block bodyStyle %} style="height: 190vh;" {% endblock bodyStyle %}
{% block body %}
<br><br>

<br><br>

<div class="container">
    <a href="/sho/home/{{request.user}}" class="btn btn-primary">HOME </a>
    <a href="/sho/approved/{{userfir.pincode}}" class="btn btn-primary"><< BACK!</a>
  </div>
  <br>
<div class="container">
    <h1 style="text-align: center;" class="fm2">FIRST INFORMATION REPORT</h1>
    <br >
    
    <form class="ml-3 mr-3" action="#" enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      <p>Date/Time: <span id="datetime">{{userfir.timestamp | naturaltime}}</span></p>
      <h4 class="fm2">FILE No: <span class="badge bg-danger">{{userfir.sno}}</span></h4>
      <div class="form-row">
        <div class="form-group col-md-12">
          <label for="name">Full Name</label>
        
      <input name="username" type="hidden" id="check" value="{{request.user}}" >
          <input type="text" class="form-control text-dark" disabled placeholder ="{{userfir.victimfullname}}" id="name"  />
        </div>
      </div>
      <div class="form-row" style="display: grid; grid-template-columns: repeat(3, 1fr); grid-column-gap: 10px;">
        <div class="form-group">
          <label for="email">Email</label>
          <input type="email" class="form-control" placeholder="{{userfir.victimemail}}" id="email" disabled />
        </div>
        <div class="form-group">
          <label for="mobile">Mobile No.</label>
          <input type="number" class="form-control" placeholder="{{userfir.mobno}}" id="mobile" disabled />
        </div>
        <div class="form-group">
          <label for="aadhar">Aadhar No.</label>
          <input type="number" class="form-control" placeholder="{{userfir.aadharno}}" id="aadhar" disabled />
        </div>
      </div>
  
      <div class="form-group">
        <label for="address">Address</label>
        <textarea type="text" class="form-control" placeholder="{{userfir.address}}" id="address" rows="4" disabled></textarea>
      </div>
      <div class="form-row" style="display: grid; grid-template-columns: 2fr 1fr 1fr; gap: 10px;">
        <div class="form-group">
          <label for="district">District</label>
          <input type="text" class="form-control" placeholder="{{userfir.district}}" id="district" disabled />
        </div>
        <div class="form-group">
          <label for="state">State</label>
          <input type="text" class="form-control" placeholder="{{userfir.state}}" id="state" disabled />
        </div>
        <div class="form-group">
          <label for="pin">Pin Code</label>
          <input type="number" class="form-control" placeholder="{{userfir.pincode}}" id="pin" disabled />
        </div>
      </div>
  
  
  
  
      <div class="form-row" style="display: grid; grid-template-columns: repeat(2, 1fr); grid-gap: 10px;">
        <div class="form-group">
          <label for="crime">Type Of Crime</label>
          <input type="text" class="form-control" placeholder="{{userfir.typeofcrime}}" id="crime" disabled />
        </div>
        <div class="form-group">
          <label for="date_incident">Date & Time of Incident</label>
          <input type="text" class="form-control" placeholder="{{userfir.incidentdatetime}}" id="date_incident" disabled />
        </div>
      </div>
  
  
  
      <div class="row">
        <div class="col-md-12">
          <label for="details">Details Of Incident</label>
          <textarea type="text" class="form-control" placeholder="{{userfir.detailsofincident}}" id="details" rows="5"
          disabled></textarea>
        </div>
      </div>
      <br />
  
  
      <div class="form-row" style="display: grid; grid-template-columns: repeat(2, 1fr); grid-gap: 10px;">
        <div class="form-group">
          <label for="suspect">Suspects</label>
          <textarea type="text" class="form-control" placeholder="{{userfir.suspect}}" id="suspect" rows="2"
          disabled></textarea>
        </div>
        <div class="form-group">
          <label for="witness">Witness</label>
          <textarea type="text" class="form-control" placeholder="{{userfir.witness}}" id="witness" rows="2"
          disabled></textarea>
        </div>
      </div>
  
  
      <div class="form-group">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" id="check" disabled checked/>
         
          <label class="form-check-label" for="check">
            I agree that all the information provided above are true to the best
            of my knowledge.
          </label>
        </div>
      </div>

      {% if userfir.solved %}
      <h3 style="text-align: center;"><span class="badge bg-success" >FIR Mark Solved by SHO, {{userfir.district}} </span></h3>
      <!-- <a class="btn btn-primary btn-block mb-5" href="/sho/fir/solved/{{userfir.sno}}">Mark Solved</a> -->
      {% elif userfir.status %}
        <h3 style="text-align: center;"><span class="badge bg-info" >Digitally Verified by SHO, {{userfir.district}} </span></h3>
        <a class="btn btn-primary btn-block mb-5" href="/sho/fir/solved/{{userfir.sno}}">Mark Solved</a>
        {% else %}
        <h3 style="text-align: center; "><span class="badge badge-info bg-warning"  >Pending</span></h3>
        <a class="btn btn-primary btn-block mb-5" href="/sho/fir/approve/{{userfir.sno}}">Approve</a>
        {% endif %}
  
        
    </form>
  </div>

  

  {% endblock body%}