FIR_Generator/FIR_Generator/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landingPage, name="landingPage"),
    path('user', include("user.urls", namespace="user")),
    path('sho', include("sho.urls", namespace="sho")),
    path('controller', include("controller.urls", namespace="controller")),
]       

FIR_Generator/sho/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "sho"
urlpatterns = [
    path('/', views.loginregister, name="shoLoginregister"),
    path('/home/<slug:slug>', views.homeSHO, name="shoHome"),

    path('/login', views.loginSHO, name="shoLogin"),
    path('/logout', views.logoutSHO, name="shoLogout"),

    path('/pending/<slug:slug>', views.pendingFIR, name="pendingFIR"),
    path('/fir/<slug:slug>', views.viewPendingFIR, name="viewPendingFIR"),
    path('/fir/approve/<slug:slug>', views.approvePendingFIR, name="approvePendingFIR"),
    path('/fir/solved/<slug:slug>', views.markSolvedFIR, name="markSolvedFIR"),



    path('/approved/<slug:slug>', views.approvedFIR, name="approvedFIR"),

    path('/searchFIR', views.searchFIR, name="searchFIR"),

    path('/solved/<slug:slug>', views.solvedFIR, name="solvedFIR"),
    

]

FIR_Generator/user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = "user"
urlpatterns = [
    path('/', views.loginregister, name="userLoginregister"),
    path('/home', views.home, name="userHome"),

    path('/login', views.loginUser, name="userLogin"),
    path('/logout', views.logoutUser, name="userLogout"),
    path('/register', views.register, name="userRegister"),

    path('/apply', views.apply, name="user-register"),
    path('/applyfir', views.applyFIR, name="userApplyFIR"),

    path('/my/<slug:slug>', views.userDashboard, name="userDashboard"),
    path('/fir/<slug:slug>', views.userFIR, name="userFIR"),


    path('/searchFIR', views.searchFIR, name="searchFIR"),
    path('/cancelFIR', views.cancelFIR, name="cancelFIR"),

    path('/otp', views.verifyotp, name="verifyotp"),





]

FIR_Generator/user/models.py
from pickle import TRUE
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now

# Create your models here.
class FIR(models.Model):
    sno= models.AutoField(primary_key=True)
    username = models.CharField(max_length=100)
    useremail = models.EmailField()
    victimemail = models.EmailField()
    victimfullname = models.CharField(max_length=100)
    mobno = models.CharField(max_length=100)
    aadharno = models.CharField(max_length=100)
    address = models.TextField()
    district = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    pincode = models.CharField(max_length=100)
    typeofcrime = models.CharField(max_length=100)
    incidentdatetime = models.DateTimeField()
    detailsofincident = models.TextField()
    suspect = models.CharField(max_length=100)
    witness = models.CharField(max_length=100)

    timestamp = models.DateTimeField(default=now)
    status = models.BooleanField(default=False)
    solved = models.BooleanField(default=False)

    def __str__(self) -> str:
        return "FIR generated by "+ self.username + " - " + self.typeofcrime

FIR_Generator/user/views.py
from django.shortcuts import render, redirect, HttpResponse,get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import FIR
from datetime import datetime
# Create your views here.

def home(request):
    return render(request,'user/landing.html')

def loginregister(request):
    
    return render(request, "user/loginregistration.html")

def loginUser(request):

    if request.method == "POST":

        email = request.POST['email']
        loginpassword = request.POST['password']
        try:
            UserData = get_object_or_404(User, email = email)
        except:
        
            
            messages.error(request, "Invalid Credentials given, Please check and retry again")
            
            return redirect('user:userLoginregister') 
        username = UserData.username 
            

        user = authenticate(username = username, password = loginpassword)
        
        if user is None:
            messages.error(request, "Invalid Credentials, Please check and retry again")
            
            return redirect('user:userLoginregister')         
        else:
            login(request,user)
            station = user.first_name
            pincode = user.last_name
            
            messages.success(request, "Successfully Logged In")
            context = {'user':username,'email':email, 'station':station, 'pincode': pincode}
            
          
            return render(request,'user/landing.html', context)
    else:
        return redirect('user:userLoginregister')
    
def logoutUser(request):
    logout(request)
    messages.success(request, "Successfully Logout")
    return redirect('/')

def register(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        

        # check for errorneous input
        if len(username)>10:

            if username.isdigit():
                messages.error(request, "Your username must contain atleast 1 character")

            messages.error(request, "Your username must be less than 10 characters")
            return redirect('user:userLoginregister')
        
        
        # Creating User
        else:
            myuser = User.objects.create_user(username = username, email = email, password=password)
            myuser.save()
            messages.success(request,"Your account has been created Successfully")
            user = authenticate(username = username, password = password)
            login(request,user)

            return render(request,'user/landing.html')
    

def apply(request):
    return render(request, 'user/apply.html')

def applyFIR(request):

    if request.method == "POST":
        username = request.POST.get('username')
        UserData = get_object_or_404(User, username = username)
        useremail = UserData.email
        fullName = request.POST.get('application[name]')
        email = request.POST.get('application[email]')
        mobNo = request.POST.get('application[mobile]')
        aadhar = request.POST.get('application[aadhar]')
        address = request.POST.get('application[address]')
        district = request.POST.get('application[district]')
        state = request.POST.get('application[state]')
        pinCode = request.POST.get('application[pin]')
        toc = request.POST.get('application[type]')
        incidentDateTime = request.POST.get('application[date]')
        
        detailsOfIncident = request.POST.get('application[details]')
        suspect = request.POST.get('application[suspect]')
        witness = request.POST.get('application[witness]')

        context = {'username':username,'useremail':useremail, 'email':email,'fullName':fullName, 'mobNo':mobNo, 'aadhar':aadhar,
                   'address':address,'district':district, 'state':state, 'pinCode':pinCode, 'toc':toc, 'incidentDateTime':incidentDateTime,
                   'detailsOfIncident':detailsOfIncident,'suspect':suspect,'witness':witness }
        return render(request,'user/otp.html',context)
        return

        
        
        fir = FIR(username=username, useremail = useremail, victimemail = email, victimfullname = fullName,
                  mobno = mobNo, aadharno = aadhar,address = address, district = district, state = state,
                  pincode = pinCode, typeofcrime = toc, incidentdatetime = incidentDateTime,
                  detailsofincident = detailsOfIncident, suspect = suspect, witness = witness)
        
        fir.save()
        messages.success(request, "Your FIR has been generated successfully")
        
    else:
        messages.error(request, "Error occured , please check and try again")
        return render(request, 'user/apply.html')

def verifyotp(request):
    if request.method == "POST":
        username = request.POST.get('username')
        useremail = request.POST.get('useremail')
        
       
        fullName = request.POST.get('fullName')
        email = request.POST.get('email')
        mobNo = request.POST.get('mobNo')
        aadhar = request.POST.get('aadhar')
        address = request.POST.get('address')
        district = request.POST.get('district')
        state = request.POST.get('state')
        pinCode = request.POST.get('pinCode')
        toc = request.POST.get('toc')
        incidentDateTime = request.POST.get('incidentDateTime')
        print(incidentDateTime)
        incidentDateTime = datetime.strptime(str(incidentDateTime), '%Y-%m-%dT%H:%M')
        print(incidentDateTime)
        detailsOfIncident = request.POST.get('detailsOfIncident')
        suspect = request.POST.get('suspect')
        witness = request.POST.get('witness')
        otp = request.POST.get('otp')

        context = {'username':username,'useremail':useremail, 'email':email,'fullName':fullName, 'mobNo':mobNo, 'aadhar':aadhar,
                'address':address,'district':district, 'state':state, 'pinCode':pinCode, 'toc':toc, 'incidentDateTime':incidentDateTime,
                'detailsOfIncident':detailsOfIncident,'suspect':suspect,'witness':witness }
        if otp != "12345678":
            messages.error(request, "You Entered Wrong OTP, Please check and try again")
            return render(request,'user/otp.html',context)
       
        fir = FIR(username=username, useremail = useremail, victimemail = email, victimfullname = fullName,
                  mobno = mobNo, aadharno = aadhar,address = address, district = district, state = state,
                  pincode = pinCode, typeofcrime = toc, incidentdatetime = incidentDateTime,
                  detailsofincident = detailsOfIncident, suspect = suspect, witness = witness)
        fir.save()

        messages.success(request, "Your FIR has been generated successfully")
        return render(request, 'user/success.html')


def userDashboard(request,slug):
    
    userfir = FIR.objects.filter(username=slug)
    len = 1
    for i in userfir:
        len += 1
    row = (len//4)+2
    height = row*60
    print(height)
   
    context = {'userfir':userfir, 'style':height}
    return render(request, 'user/my.html', context)
    
    
def userFIR(request,slug):

    userfir = get_object_or_404(FIR, sno = int(slug))

    context = {'userfir':userfir}
    return render(request, 'user/viewfir.html', context)


def searchFIR(request):
        
    if request.method == "POST":
        username = request.POST.get('username')
        from_date = request.POST.get('date[from]')
        to_date = request.POST.get('date[to]')
        selected_values = request.POST.get('status')
        print(selected_values)
        start_date = datetime.strptime(str(from_date), '%Y-%m-%d')
        end_date = datetime.strptime(str(to_date), '%Y-%m-%d')
        records = FIR.objects.filter(incidentdatetime__range=(start_date, end_date), username = username)
        if 'pending' in selected_values:
            records = FIR.objects.filter(incidentdatetime__range=(start_date, end_date), username = username, status = False )
        elif 'approved' in selected_values:
            records = FIR.objects.filter(incidentdatetime__range=(start_date, end_date), username = username, status = True )
        elif 'solved' in selected_values:
            records = FIR.objects.filter(incidentdatetime__range=(start_date, end_date), username = username, solved = True )
        else:
            records = FIR.objects.filter(incidentdatetime__range=(start_date, end_date), username = username, )
            
        messages.success(request, f"Showing {selected_values} results from {from_date} to {to_date}")
        context = {'userfir': records}
        return render(request, 'user/search.html', context)
    
    return render(request, 'user/search.html')


def cancelFIR(request):
    return render(request, 'user/cancel.html')
        

FIR_Generator/templates/user/apply.html
{% extends 'header.html' %}
{% load static %}
{% block navimg %}
<img src="{% static 'user_avt.png' %}" alt="Person" width="96" height="96">
{% endblock navimg %}
{% block bodyStyle %}style="height: 150vh;justify-content: start"{% endblock bodyStyle %}
{% block body %}

    
<div class="container mt-5">
  <a href="/user/home" class="btn btn-primary">
     HOME </a>
</div>  

<div class="container">
  <h1 class="fm2" style="text-align: center; ">APPLICATION FORM</h1>
  <br />
  <p name="appliation[fileno]"></p>
  <p name="appliation[success]"></p>
  <form class="ml-3 mr-3" action="{% url 'user:userApplyFIR' %}" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <p>Date/Time: <span id="datetime"></span></p>
    <div class="form-row">
      <div class="form-group col-md-12">
        <label for="name">Full Name</label>
      
    <input name="username" type="hidden" id="check" value="{{request.user}}" >
        <input type="text" class="form-control" name="application[name]" id="name" required />
      </div>
    </div>
    <div class="form-row" style="display: grid; grid-template-columns: repeat(3, 1fr); grid-column-gap: 10px;">
      <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" name="application[email]" id="email" required />
      </div>
      <div class="form-group">
        <label for="mobile">Mobile No. </label>
        <input type="number" class="form-control" name="application[mobile]" id="mobile" required />
      </div>
      <div class="form-group">
        <label for="aadhar">Aadhar No.</label>
        <input type="number" class="form-control" name="application[aadhar]" id="aadhar" required />
      </div>
    </div>

    <div class="form-group">
      <label for="address">Address</label>
      <textarea type="text" class="form-control" name="application[address]" id="address" rows="4" required></textarea>
    </div>
    <div class="form-row" style="display: grid; grid-template-columns: 2fr 1fr 1fr; gap: 10px;">
      <div class="form-group">
        <label for="district">District</label>
        <input type="text" class="form-control" name="application[district]" id="district" required />
      </div>
      <div class="form-group">
        <label for="state">State</label>
        <input type="text" class="form-control" name="application[state]" id="state" required />
      </div>
      <div class="form-group">
        <label for="pin">Pin Code</label>
        <input type="number" class="form-control" name="application[pin]" id="pin" required />
      </div>
    </div>




    <div class="form-row" style="display: grid; grid-template-columns: repeat(2, 1fr); grid-gap: 10px;">
      <div class="form-group">
        <label for="crime">Type Of Crime</label>
        <input type="text" class="form-control" name="application[type]" id="crime" required />
      </div>
      <div class="form-group">
        <label for="date_incident">Date & Time of Incident</label>
        <input type="datetime-local" class="form-control" name="application[date]" id="date_incident" required />
      </div>
    </div>



    <div class="row">
      <div class="col-md-12">
        <label for="details">Details Of Incidence</label>
        <textarea type="text" class="form-control" name="application[details]" id="details" rows="5"
          required></textarea>
      </div>
    </div>
    <br />


    <div class="form-row" style="display: grid; grid-template-columns: repeat(2, 1fr); grid-gap: 10px;">
      <div class="form-group">
        <label for="suspect">Suspects</label>
        <textarea type="text" class="form-control" name="application[suspect]" id="suspect" rows="2"
          required></textarea>
      </div>
      <div class="form-group">
        <label for="witness">Witness</label>
        <textarea type="text" class="form-control" name="application[witness]" id="witness" rows="2"
          required></textarea>
      </div>
    </div>




    <!-- <label class="custom-file-label" for="file">Upload Your Signature:</label>    -->
    <!-- <input type="file" name="application[file]" class="custom-file-input" id="fisle"/> <br>  -->
    {% comment %} <div class="custom-file mb-3 m-auto">
      <input type="file" name="application[file]" id="file" class="custom-file-input" required /> {% endcomment %}
      {% comment %} <label for="file" class="custom-file-label">Upload Your Signature</label> {% endcomment %}
      {% comment %}
    </div> {% endcomment %}

    <div class="form-group">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="check" required />
       
        <label class="form-check-label" for="check">
          I agree that all the information provided above are true to the best
          of my knowledge.
        </label>
      </div>
    </div>
<br>
    <button type="submit" class="btn btn-primary form-control" > Submit</button>
  </form>
</div>

{% endblock body %}

FIR_Generator/templates/user/cancel.html
{% extends 'header.html' %}
{% load static %}
{% load humanize %}
{% block navimg %}
<img src="{% static 'user_avt.png' %}" alt="Person" width="96" height="96">
{% endblock navimg %}
{% block bodyStyle %} style="height: 100vh;" {% endblock bodyStyle %}
{% block body %}



<div class="container">
   
    <div class="container">
      <a href="/user/home" class="btn btn-primary"> HOME </a>
    </div>
    <h1 style="text-align: center;" class="fm2">CANCEL FORM</h1>
    <div style="width: 60%; margin: 30px auto;">
      <h3>
        If you want to cancel the FIR, you must understand that the Police cannot
        take back an FIR, it can be done only in the courts. You must appear in
        the court and express your intention to compound the offence, either to
        the judge or to the lawyer of opposing party or to the court officials who
        are present.
      </h3>
      <a
        class="btn btn-info btn-lg btn-block mt-5"
        style="text-align: center;"
        href="https://www.quora.com/How-do-I-cancel-an-FIR-and-do-I-have-to-pay-for-its-cancellation-If-so-then-to-whom-the-police-or-the-court"
      >
        LEARN MORE
      </a>
    </div>
  </div>
  {% endblock body %}

FIR_Generator/templates/user/landing.html
{% extends 'header.html' %}
{% load static %}
{% block navimg %}
<img src="{% static 'user_avt.png' %}" alt="Person" width="96" height="96">
{% endblock navimg %}
{% block bodyStyle %}style="height: 100vh;justify-content: start;"{% endblock bodyStyle %}


{% block body %}


<div class="">
    <hr>

    <div class="container">
        <div class="row">
            <div class="col-sm-2">
                <img class="img-responsive pt-2" style="width: 10em; height: 6em;"
                    src="{% static 'main/firgenlogo.jpg' %}" alt="No" />
            </div>
            <div class="col-sm-1 vl"></div>
            <div class="col-sm-9 head">
                <h4 class="fm2">ONLINE FIR GENERATOR</h4>
                <p>Department Of Complaint</p>
            </div>
        </div>
    </div>

    <hr class="mt-0 mb-1" />
    <nav class="navbar navbar-expand-lg navbar-light sec-nav" style="background-color: #f3e3ae96;">
        <a class="nav-link" href="#">About Us</a>
        <!-- <a class="nav-link" href="/my">My Dashboard</a> -->
        <!-- <a class="nav-link" href="#">Downloads</a> -->
        <a class="nav-link" href="#">Help</a>
        <a class="nav-link" href="#">Frequently Asked Questions</a>
        <a class="nav-link" href="#">Contact & Support</a>
    </nav>
    <br />
    <div class="container sv">
        <div class="row">
            <div class="col-sm-6 d-grid gap-2">
                <a class=" btn btn-outline-dark btn-lg btn-block fm" href="/user/apply">Apply Online</a>
            </div>
            <div class="col-sm-6 d-grid gap-2">
                <a class=" btn btn-outline-dark btn-lg btn-block fm" href="/user/my/{{request.user}}">My
                    Dashboard</a>

            </div>
        </div>
        <div class=" row">
            <div class="col-sm-6 d-grid gap-2">
                <a class="btn btn-outline-dark btn-lg btn-block fm" href="/user/searchFIR">Search FIR</a>
            </div>
            <div class="col-sm-6 d-grid gap-2">
                <a class="btn btn-outline-dark btn-lg btn-block fm" href="/user/cancelFIR">Cancel Application</a>
            </div>
        </div>
    </div>
</div>

</div>



{% endblock body %}

FIR_Generator/templates/user/loginregistration.html
{% extends 'footer.html' %}

{% load static %}
<!-- {% block style %} 'loginregister/loginregister.css'{% endblock style %} -->
{% block nav_content %}

<div style="justify-content: space-around;display: flex;">
  <a class="btn btn-dark  ml-2" style=" height: 100%; " href="/"> Back </a>
</div>
{% endblock nav_content %}
{% block body %}

  <div class="container login " id="container">
    <div class="form-container sign-up-container">

      <form action="{% url 'user:userRegister' %}" method="POST"> {% csrf_token %}
        <h1>Create Account</h1>
        <div class="social-container">
          <a href="#" class="social"><i class="fa fa-facebook"></i></a>
          <a href="#" class="social"><i class="fa fa-google"></i></a>
          <a href="#" class="social"><i class="fa fa-linkedin"></i></a>
        </div>
        <span>or use your email for registration</span>
        <input type="email" placeholder="Email" name="email" />
        <input type="text" placeholder="UserName" name="username" />
        <input type="password" placeholder="Password" name="password" />
        <button>Sign Up</button>
      </form>
    </div>
    <div class="form-container sign-in-container">

      <form action="{% url 'user:userLogin' %}" method="POST"> {% csrf_token %}
        <h1>Sign in</h1>
        <div class="social-container">
          <a href="#" class="social"><i class="fa fa-facebook"></i></a>
          <a href="#" class="social"><i class="fa fa-google"></i></a>
          <a href="#" class="social"><i class="fa fa-linkedin"></i></a>
        </div>
        <span>or use your account</span>
        <input type="email" placeholder="Email" name="email" />
        <input type="password" placeholder="Password" name="password" />
        <a href="#">Forgot your password?</a>
        <button>Sign In</button>
      </form>
    </div>
    <div class="overlay-container">
      <div class="overlay">
        <div class="overlay-panel overlay-left">
          <h1>Welcome Back!</h1>
          <p>Login here with your personal info</p>
          <button class="ghost" id="signIn">Sign In</button>
        </div>
        <div class="overlay-panel overlay-right">
          <h1>New User?</h1>
          <p>Enter your personal details to get signed up</p>
          <button class="ghost" id="signUp">Sign Up</button>
        </div>
      </div>
    </div>
  </div>
  
  <script src="{% static 'loginregister/loginregister.js' %}"></script>
  {% endblock body %}

FIR_Generator/templates/user/my.html
{% extends 'header.html' %}
{% load static %}
{% load humanize %}
{% block navimg %}
<img src="{% static 'user_avt.png' %}" alt="Person" width="96" height="96">
{% endblock navimg %}
{% block bodyStyle %} style="height: 100vh; overflow-x: hidden;justify-content: start" {% endblock bodyStyle %}
{% block body %}


<div class="mt-5">
  <div class="container ">
    <a href="/user/home" class="btn btn-primary">
      HOME </a>
  </div>

  <h1 class="text-center mb-2 fm2">My Reports</h1>
  <!-- style="display: grid; grid-template-columns: repeat(auto-fit, minmax(18rem, 1fr)); justify-items: center; align-items: center; gap: 20px;" -->
  <div class="row text-center  row row-cols-1 row-cols-sm-2 row-cols-lg-4 g-4 m-4">
    {% for fir in userfir %}
    <div class="col border border-dark border-1 rounded-3  shadow-lg p-3 mb-5 bg-body rounded">
      <div class=" card shadow-lg ">
        <div class="card-body">
          <h5 class="card-title ">Application No. : <mark class="bg-danger">{{fir.sno}}</mark></h5>
          <p class="card-text">Details: {{fir.typeofcrime}}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Complaint Date: {{fir.timestamp | naturaltime}}</li>
          <li class="list-group-item">Crime Date: {{fir.incidentdatetime}}</li>
        </ul>
        <div class="card-body">
          {% if fir.solved %}
          <span class="badge bg-success  fs-5  text-wrap">Marked Solved by SHO, {{fir.district}} </span>
          {% elif fir.status %}


          <span class="badge bg-success  fs-5  text-wrap">Digitally Verified by SHO</span>

          {% else %}
          <span class="badge bg-warning  fs-5 text-wrap">Pending</span>
          {% endif %}
          <hr>
          <a href="/user/fir/{{fir.sno}}" class="btn btn-primary btn-block">View/Download Complaint</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>


  {% endblock body %}

FIR_Generator/templates/user/otp.html
{% extends 'header.html' %}
{% load static %}
{% block navimg %}
<img src="{% static 'user_avt.png' %}" alt="Person" width="96" height="96">
{% endblock navimg %}
{% block bodyStyle %}style="height: 100vh;margin-top:-20px"{% endblock bodyStyle %}
{% block body %}

<div class="container ">

  <a href="/user/home" class="btn btn-primary"><< HOME!</a>
    <a href="/user/apply" class="btn btn-danger"><< Cancel FIR!</a>
   
  </div>

<div class="container " id="otp">

    <h1 class="fm2" style="text-align: center;">OTP Verification for FIR</h1>
    <h5>
      A message has been sent to your registered mobile number. Type the code to
      confirm your identity. Remember to fill it correctly else you will need to
      fill the form again. (Currently it is set to: 12345678)
    </h5>
    <form class="form-inline " action="{% url 'user:verifyotp' %}" method="POST"> {% csrf_token %}
      <div class="form-group mb-2 justify-content-center">
        <label for="inputPassword2" class="sr-only">Password</label>
        <input
          type="text"
          class="form-control"
          id="otp"
          placeholder="OTP"
          name="otp"
          required
        />
        
      </div>
      <input type="hidden" name="username"  value="{{username}}">
      <input type="hidden" name="useremail"  value="{{useremail}}">
      <input type="hidden" name="email"  value="{{email}}">
      <input type="hidden" name="fullName"  value="{{fullName}}">
      <input type="hidden" name="mobNo"  value="{{mobNo}}">
      <input type="hidden" name="aadhar"  value="{{aadhar}}">
      <input type="hidden" name="address"  value="{{address}}">
      <input type="hidden" name="district"  value="{{district}}">
      <input type="hidden" name="state"  value="{{state}}">
      <input type="hidden" name="pinCode"  value="{{pinCode}}">
      <input type="hidden" name="toc"  value="{{toc}}">
      <input type="hidden" name="incidentDateTime"  value="{{incidentDateTime}}">
      <input type="hidden" name="detailsOfIncident"  value="{{detailsOfIncident}}">
      <input type="hidden" name="suspect"  value="{{suspect}}">
      <input type="hidden" name="witness"  value="{{witness}}">
      <button type="submit" class="btn btn-primary ">Confirm identity</button>
    </form>
  </div>
  <br>

  {% endblock body %}

FIR_Generator/templates/user/search.html
{% extends 'header.html' %}
{% load static %}
{% load humanize %}
{% block navimg %}
<img src="{% static 'user_avt.png' %}" alt="Person" width="96" height="96">
{% endblock navimg %}

{% block bodyStyle %} style="height: 100vh;justify-content: start" {% endblock bodyStyle %}
{% block body %}

<style>
  .checkbox {
    transform: scale(1.5);
    margin-right: 10px;
  }
</style>

<div class="container mt-5">
    <a href="/user/home" class="btn btn-primary"> HOME </a>
  </div>
  
  <div class="container" >
    <h1 style="text-align: center;" class="fm2">Search FIR's Between Dates</h1>
    <br />
    <center>
    <form action="{% url 'user:searchFIR' %}" method="POST" > {% csrf_token %}
      <div class="form-row" style="justify-content: start;">  
        <div class="form-group col-md-6">
          <label for="fromdate">From Date</label>
          <input
            type="date"
            class="form-control mb-2 mr-sm-2"
            id="fromdate"
            name="date[from]"
            required
          />
        </div>
      </div>
  
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="todate">To Date</label>
          <input
            type="date"
            class="form-control mb-2 mr-sm-2"
            id="todate"
            name="date[to]"
            required
          />
        </div>
      </div>
      <input type="hidden" name="username" value="{{request.user}}">
      <label class="m-1">
        <input type="radio" name="status" value="All" class="checkbox">
        All
      </label>
      <label class="m-1">
        <input type="radio" name="status" value="pending" class="checkbox">
        Pending
      </label>
    
      <label class="m-1">
        <input type="radio" name="status" value="approved" class="checkbox">
        Approved
      </label>
    
      <label class="m-1">
        <input type="radio" name="status" value="solved" class="checkbox">
        Solved
      </label >
      
      <button type="submit" class="btn btn-primary mb-2">Search</button>
    </form>
  </center>
  </div>

  <h1 class="text-center mb-2 fm2">Searched Results</h1>
  <!-- style="display: grid; grid-template-columns: repeat(auto-fit, minmax(18rem, 1fr)); justify-items: center; align-items: center; gap: 20px;" -->
  <div class="row text-center  row row-cols-1 row-cols-sm-2 row-cols-lg-4 g-4 m-4">
    {% for fir in userfir %}
    <div class="col border border-dark border-1 rounded-3  shadow-lg p-3 mb-5 bg-body rounded">
      <div class=" card shadow-lg ">
        <div class="card-body">
          <h5 class="card-title ">Application No. : <mark class="bg-danger">{{fir.sno}}</mark></h5>
          <p class="card-text">Details: {{fir.typeofcrime}}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Complaint Date: {{fir.timestamp | naturaltime}}</li>
          <li class="list-group-item">Crime Date: {{fir.incidentdatetime}}</li>
        </ul>
        <div class="card-body">
          {% if fir.solved %}
          <span class="badge bg-success  fs-5  text-wrap">Marked Solved by SHO, {{fir.district}} </span>
          {% elif fir.status %}


          <span class="badge bg-success  fs-5  text-wrap">Digitally Verified by SHO</span>

          {% else %}
          <span class="badge bg-warning  fs-5 text-wrap">Pending</span>
          {% endif %}
          <hr>
          <a href="/user/fir/{{fir.sno}}" class="btn btn-primary btn-block">View/Download Complaint</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  {% endblock body %}
  