FIR_Generator/FIR_Generator/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landingPage, name="landingPage"),
    path('user', include("user.urls", namespace="user")),
    path('sho', include("sho.urls", namespace="sho")),
    path('controller', include("controller.urls", namespace="controller")),
]       

FIR_Generator/controller/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "controller"
urlpatterns = [
    path('', views.loginregister, name="controllerLoginregister"),
    path('/home', views.homeController, name="controllerHome"),

    path('/login', views.loginController, name="controllerLogin"),
    path('/logout', views.logoutController, name="controllerLogout"),


    path('/searchFIR', views.searchFIR, name="searchFIR"),
    path('/manageSHO', views.manageSHO, name="manageSHOaccount"),
    path('/viewSHO/<slug:slug>', views.viewSHOdetails, name="viewSHOdetails"),
    path('/createsho', views.createSHO, name="newSHOaccount"),
    path('/editSHO', views.editSHO, name="editSHOaccount"),
    path('/newsho', views.newSHO, name="newsho"),
    path('/deleteSHOaccount/<slug:slug>', views.deleteSHO, name="deleteSHOaccount"),

]

FIR_Generator/sho/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "sho"
urlpatterns = [
    path('/', views.loginregister, name="shoLoginregister"),
    path('/home/<slug:slug>', views.homeSHO, name="shoHome"),

    path('/login', views.loginSHO, name="shoLogin"),
    path('/logout', views.logoutSHO, name="shoLogout"),

    path('/pending/<slug:slug>', views.pendingFIR, name="pendingFIR"),
    path('/fir/<slug:slug>', views.viewPendingFIR, name="viewPendingFIR"),
    path('/fir/approve/<slug:slug>', views.approvePendingFIR, name="approvePendingFIR"),
    path('/fir/solved/<slug:slug>', views.markSolvedFIR, name="markSolvedFIR"),



    path('/approved/<slug:slug>', views.approvedFIR, name="approvedFIR"),

    path('/searchFIR', views.searchFIR, name="searchFIR"),

    path('/solved/<slug:slug>', views.solvedFIR, name="solvedFIR"),
    

]

FIR_Generator/controller/models.py
from django.db import models

# Create your models here.

FIR_Generator/controller/views.py
from django.shortcuts import render, redirect, HttpResponse,get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from user.models import FIR
from datetime import datetime
# Create your views here.


def loginregister(request):
    return render(request, "controller/loginregistration.html")

def homeController(request,):
    return render(request, 'controller/landing.html')

def loginController(request):

    if request.method == "POST":

        email = request.POST['email']
        loginpassword = request.POST['password']
       
        UserData = get_object_or_404(User, email = email)
        
        if UserData is None:
            messages.error(request, "Invalid Credentials, Please check and retry again")
            
            return render('controller:controllerLoginregister') 
        username = UserData.username 
            

        user = authenticate(username = username, password = loginpassword)
        
        if user is None:
            messages.error(request, "Invalid Credentials, Please check and retry again")
            
            return redirect('controller:controllerLoginregister')         
        else:
            login(request,user)
            print('admin')
           
            
            messages.success(request, "Successfully Logged In")
            context = {'user':username,'email':email, }
            
          
            return render(request,'controller/landing.html', context)
    else:
        return redirect('controller:controllerLoginregister')
 

def logoutController(request):
    logout(request)
    messages.success(request, "Successfully Logout")
    return redirect('/')


def searchFIR(request):
    return render(request, 'controller/search.html')


def manageSHO(request):
    users = User.objects.exclude(last_name__exact='').exclude(last_name__isnull=True)
    context ={'user':users}

    for i in users:
        print(i.last_name)
    return render(request, 'controller/managesho.html', context)

def viewSHOdetails(request, slug):
    sho = get_object_or_404(User, username = slug )
    context = {'sho':sho}
    return render(request, 'controller/viewsho.html', context)


def createSHO(request):
    return render(request, 'controller/createsho.html')
    
def editSHO(request):
    if request.method == "POST":
        oldusername = request.POST['oldusername']
        sho = get_object_or_404(User, username = oldusername)

        email = request.POST['email']
        psw = request.POST['psw']
        username = request.POST['username']
        paddress = request.POST['paddress']
        ppin = request.POST['ppin']

        if email:
            sho.email = email
        if psw:
            sho.password = psw
        if username :
            sho.username = username
        if paddress:
            sho.first_name = paddress
        if ppin :
            sho.last_name = ppin

        sho.save()
        messages.success(request, 'Selected SHO Details Modified Successfully')
        return redirect('controller:manageSHOaccount')

        

def deleteSHO(request,slug):
    sho = User.objects.get(username=slug)
    sho.delete()
    messages.success(request, f' SHO Account of {slug} deleted Successfully')
    return redirect('controller:manageSHOaccount')


def newSHO(request):

    if request.method == "POST":

        email = request.POST['email']
        psw = request.POST['psw']
        pswrepeat = request.POST['psw-repeat']
        if psw != pswrepeat:
            messages.error(request,"Your Password didn't match")
            return redirect('controller:newSHOaccount')
        username = request.POST['username']
        paddress = request.POST['paddress']
        ppin = request.POST['ppin']

        newsho = User.objects.create_user(username=username,email=email,password=psw, first_name = paddress, last_name = ppin )
        newsho.save()
        messages.success(request,"New SHO account has been created Successfully")

        return render(request,'controller/createsho.html')
       

    return redirect('controller:newSHOaccount')
    

FIR_Generator/templates/controller/createsho.html
{% extends 'header.html' %}
{% load static %}
{% block navimg %}
<img src="{% static 'admin_avt.png' %}" alt="Person" width="96" height="96">
{% endblock navimg %}
{% block bodyStyle %}style="height: 100vh;justify-content: start;"{% endblock bodyStyle %}


{% block body %}
<style>
    * {
        box-sizing: border-box;
    }

    /* Add padding to containers */
    .container {
        padding: 16px;
        background-color: transparent;
    }

    /* Full-width input fields */
    input[type=text],
    input[type=password] {
        width: 100%;
        padding: 15px;
        margin: 5px 0 22px 0;
        display: inline-block;
        border: none;
        background: #f1f1f1;
    }

    input[type=text]:focus,
    input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    /* Overwrite default styles of hr */
    hr {
        border: 1px solid #f1f1f1;
        margin-bottom: 25px;
    }

    /* Set a style for the submit button */
    .registerbtn {
        background-color: #04AA6D;
        color: white;
        padding: 16px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 100%;
        opacity: 0.9;
    }

    .registerbtn:hover {
        opacity: 1;
    }

    /* Add a blue text color to links */
    a {
        color: dodgerblue;
    }

    /* Set a grey background color and center the text of the "sign in" section */
    .signin {
        background-color: #f1f1f1;
        text-align: center;
    }
</style>
<br>
<div class="container mt-5">
    <a href="/controller/home" class="btn btn-primary"> HOME!</a>
    <a href="/controller/manageSHO" class="btn btn-primary"><< BACK </a>
  </div>

<div>

    <form action="{% url 'controller:newsho' %}" method="POST" enctype="multipart/form-data" style="background-color: transparent;"> {% csrf_token %}
        <div class="container">
            <h1 class="fm2" style="text-align: center;">Create New SHO Account</h1>
            <p style="text-align: center;">Please fill in this form to create an account.</p>
            <hr>

            <label for="email"><b>Email</b></label>
            <input type="text" placeholder="Enter Email" name="email" id="email" required>
            <label for="email"><b>UserName</b></label>
            <input type="text" placeholder="Enter Email" name="username" id="username" required>
            <label for="email"><b>Police Station Address</b></label>
            <input type="text" placeholder="Enter Email" name="paddress" id="paddress" required>
            <label for="email"><b>Police Station PINCODE</b></label>
            <input type="text" placeholder="Enter Email" name="ppin" id="ppin" required>

            <label for="psw"><b>Password</b></label>
            <input type="password" placeholder="Enter Password" name="psw" id="psw" required>

            <label for="psw-repeat"><b>Repeat Password</b></label>
            <input type="password" placeholder="Repeat Password" name="psw-repeat" id="psw-repeat" required>
            
            <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>

            <button type="submit" class="registerbtn">Register</button>
        </div>

        <div class="container signin">
            <p>Already have an account? <a href="/controller/logout">Sign in</a>.</p>
        </div>
    </form>
</div>
{% endblock body %}

FIR_Generator/templates/controller/landing.html
{% extends 'header.html' %}
{% load static %}
{% block navimg %}
<img src="{% static 'admin_avt.png' %}" alt="Person" width="96" height="96">
{% endblock navimg %}

{% block bodyStyle %}style="height: 100vh;justify-content: start;"{% endblock bodyStyle %}


{% block body %}

<hr>
<div>

    <div class="container">
        <div class="row">
            <div class="col-sm-2">
                <img class="img-responsive pt-2" style="width: 10em; height: 6em;"
                    src="{% static 'main/firgenlogo.jpg' %}" alt="No" />
            </div>
            <div class="col-sm-1 vl"></div>
            <div class="col-sm-9 head">
                <h4 class="fm2">ONLINE FIR GENERATOR</h4>
                <p>Department Of Complaint</p>
            </div>
        </div>
    </div>

    <hr class="mt-0 mb-1" />
    <nav class="navbar navbar-expand-lg navbar-light sec-nav" style="background-color: #f3e3ae96;">
        <a class="nav-link" href="#">About Us</a>
        <!-- <a class="nav-link" href="/my">My Dashboard</a> -->
        <!-- <a class="nav-link" href="#">Downloads</a> -->
        <a class="nav-link" href="#">Help</a>
        <a class="nav-link" href="#">Frequently Asked Questions</a>
        <a class="nav-link" href="#">Contact & Support</a>
    </nav>
    <br />
    <div class="container sv">
        <h3 class="fm2" style="text-align: center;">Welcome to the Admin Page of Online FIR Generator</h3>
        <div class="row">
            <div class="col-sm-6 d-grid gap-2">
                <a class=" btn btn-outline-dark btn-lg btn-block fm" href="/controller/manageSHO">Manage SHO Account</a>
            </div>
            <div class="col-sm-6 d-grid gap-2">
                <a class=" btn btn-outline-dark btn-lg btn-block fm" href="/sho/approved/{{pincode}}">Manage FIR Reports</a>

            </div>
        </div>
        <div class=" row">
            <div class="col-sm-6 d-grid gap-2">
                <a class="btn btn-outline-dark btn-lg btn-block fm" href="/controller/searchFIR">Search FIR</a>
            </div>
            <div class="col-sm-6 d-grid gap-2">
                <a class="btn btn-outline-dark btn-lg btn-block fm" href="/sho/solved/{{pincode}}">Solved FIR</a>
            </div>
        </div>
    </div>
</div>

</div>



{% endblock body %}

FIR_Generator/templates/controller/loginregistration.html
{% extends 'footer.html' %}

{% load static %}

{% block nav_content %}

<div style="justify-content: space-around;display: flex;">
  <a class="btn btn-dark  ml-2" style=" height: 100%; " href="/"> Back </a>
</div>

{% endblock nav_content %}

{% block body %}
<br><br>

  <div class="container login mt-5 " id="container">
    
    <div class="form-container sign-in-container">

      <form action="/controller/login" method="POST"> {% csrf_token %}
        <h1>Sign in</h1>
        <div class="social-container">
          <a href="#" class="social"><i class="fa fa-facebook"></i></a>
          <a href="#" class="social"><i class="fa fa-google"></i></a>
          <a href="#" class="social"><i class="fa fa-linkedin"></i></a>
        </div>
        <span>or use your account</span>
        <input type="email" placeholder="Email" name="email" />
        <input type="password" placeholder="Password" name="password" />
        <a href="#">Forgot your password?</a>
        <button>Sign In</button>
      </form>
    </div>
    <div class="overlay-container">
      <div class="overlay">
        
        <div class="overlay-panel overlay-right">
          <h1>Welcome to the Online FIR generator</h1>
          <p>Enter your credential to get signed in</p>
          
        </div>
      </div>
    </div>
  </div>
  
  <script src="{% static 'loginregister/loginregister.js' %}"></script>
  {% endblock body %}

FIR_Generator/templates/controller/managesho.html
{% extends 'header.html' %}
{% load static %}
{% load humanize %}
{% block navimg %}
<img src="{% static 'admin_avt.png' %}" alt="Person" width="96" height="96">
{% endblock navimg %}
{% block bodyStyle %} style="height: 100vh; overflow-x: hidden;justify-content: start" {% endblock bodyStyle %}
{% block body %}

<br>
<div class="container">
  <a href="/controller/home" class="btn btn-primary">
     HOME!</a>  
     
  <a href="/controller/createsho" class="btn btn-primary" style="float: right;">
    Create New SHO Account</a>
</div>

<center><h2 class="fm2"> SHO Account Details</h2></center>
<div class="m-2">

    <div style="height: 350px; overflow: auto;" id="" class="border border-danger border-3 p-2">
        <div class="d-grid">
            <a class="btn btn-danger"  >
                <div class="row ">
                    <div class="col">UserName
                    </div>
                    <div class="col">SHO Address</div>
                    <div class="col">SHO Pincode</div>
                </div>
            </a>
        </div>
        {% for sho in user %}
        
        <div class="d-grid">
            <a class="btn btn-outline-dark" href="/controller/viewSHO/{{sho.username}}" >
                <div class="row ">
                    <div class="col">{{ sho.username }}
                    </div>
                    <div class="col">{{sho.first_name}}</div>
                    <div class="col">{{sho.last_name}}</div>
                </div>
            </a>
        </div>
     

        {% endfor %}
    </div>

    

   
</div>

{% endblock body %}

FIR_Generator/templates/controller/search.html
{% extends 'header.html' %}
{% load static %}
{% load humanize %}
{% block navimg %}
<img src="{% static 'admin_avt.png' %}" alt="Person" width="96" height="96">
{% endblock navimg %}

{% block bodyStyle %} style="height: 100vh;justify-content: start" {% endblock bodyStyle %}
{% block body %}

<style>
  .checkbox {
    transform: scale(1.5);
    margin-right: 10px;
  }
</style>

<div class="container mt-5">
    <a href="/controller/home" class="btn btn-primary"> HOME </a>
  </div>
  
  <div class="container" >
    <h1 style="text-align: center;" class="fm2">Search FIR's Between Dates</h1>
    <br />
    <center>
    <form action="{% url 'user:searchFIR' %}" method="POST" > {% csrf_token %}
      <div class="form-row" style="justify-content: start;">  
        <div class="form-group col-md-6">
          <label for="fromdate">From Date</label>
          <input
            type="date"
            class="form-control mb-2 mr-sm-2"
            id="fromdate"
            name="date[from]"
            required
          />
        </div>
      </div>
  
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="todate">To Date</label>
          <input
            type="date"
            class="form-control mb-2 mr-sm-2"
            id="todate"
            name="date[to]"
            required
          />
        </div>
      </div>
      <input type="hidden" name="username" value="{{request.user}}">
      <label class="m-1">
        <input type="radio" name="status" value="All" class="checkbox">
        All
      </label>
      <label class="m-1">
        <input type="radio" name="status" value="pending" class="checkbox">
        Pending
      </label>
    
      <label class="m-1">
        <input type="radio" name="status" value="approved" class="checkbox">
        Approved
      </label>
    
      <label class="m-1">
        <input type="radio" name="status" value="solved" class="checkbox">
        Solved
      </label >
      
      <button type="submit" class="btn btn-primary mb-2">Search</button>
    </form>
  </center>
  </div>

  <h1 class="text-center mb-2 fm2">Searched Results</h1>
  <!-- style="display: grid; grid-template-columns: repeat(auto-fit, minmax(18rem, 1fr)); justify-items: center; align-items: center; gap: 20px;" -->
  <div class="row text-center  row row-cols-1 row-cols-sm-2 row-cols-lg-4 g-4 m-4">
    {% for fir in userfir %}
    <div class="col border border-dark border-1 rounded-3  shadow-lg p-3 mb-5 bg-body rounded">
      <div class=" card shadow-lg ">
        <div class="card-body">
          <h5 class="card-title ">Application No. : <mark class="bg-danger">{{fir.sno}}</mark></h5>
          <p class="card-text">Details: {{fir.typeofcrime}}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Complaint Date: {{fir.timestamp | naturaltime}}</li>
          <li class="list-group-item">Crime Date: {{fir.incidentdatetime}}</li>
        </ul>
        <div class="card-body">
          {% if fir.solved %}
          <span class="badge bg-success  fs-5  text-wrap">Marked Solved by SHO, {{fir.district}} </span>
          {% elif fir.status %}


          <span class="badge bg-success  fs-5  text-wrap">Digitally Verified by SHO</span>

          {% else %}
          <span class="badge bg-warning  fs-5 text-wrap">Pending</span>
          {% endif %}
          <hr>
          <a href="/user/fir/{{fir.sno}}" class="btn btn-primary btn-block">View/Download Complaint</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  {% endblock body %}
  

FIR_Generator/templates/controller/viewsho.html
{% extends 'header.html' %}
{% load static %}
{% block navimg %}
<img src="{% static 'admin_avt.png' %}" alt="Person" width="96" height="96">
{% endblock navimg %}
{% block bodyStyle %}style="height: 150vh;overflow-x: hidden;justify-content: start"{% endblock bodyStyle %}


{% block body %}
<style>
    * {
        box-sizing: border-box;
    }

    /* Add padding to containers */
    .container {
        padding: 16px;
        background-color: transparent;
    }

    /* Full-width input fields */
    input[type=text],
    input[type=password] {
        width: 100%;
        padding: 15px;
        margin: 5px 0 22px 0;
        display: inline-block;
        border: none;
        background: #f1f1f1;
    }

    input[type=text]:focus,
    input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    /* Overwrite default styles of hr */
    hr {
        border: 1px solid #f1f1f1;
        margin-bottom: 25px;
    }

    /* Set a style for the submit button */
    .registerbtn {
        background-color: #04AA6D;
        color: white;
        padding: 16px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 100%;
        opacity: 0.9;
    }

    .registerbtn:hover {
        opacity: 1;
    }

    /* Add a blue text color to links */
    a {
        color: dodgerblue;
    }

    /* Set a grey background color and center the text of the "sign in" section */
    .signin {
        background-color: #f1f1f1;
        text-align: center;
    }
</style>    

<div class="container mt-5">
    <a href="/controller/home" class="btn btn-primary"> HOME!</a>
    <a href="/controller/manageSHO" class="btn btn-primary"><< BACK </a>
  </div>

<div>

    <form action="{% url 'controller:editSHOaccount' %}" method="POST" enctype="multipart/form-data" style="background-color: transparent;"> {% csrf_token %}
        <div class="container">
            <h1 class="fm2" style="text-align: center;">Selected SHO Account Details</h1>
            <p style="text-align: center;">Change value in this form to edit details of the SHO account.</p>
            <hr>
            <input type="hidden" name="oldusername" value="{{sho.username}}">
            <label for="email"><b>Email</b></label>
            <input type="text" placeholder="{{sho.email}}" name="email" id="email" >
            <label for="email"><b>UserName</b></label>
            <input type="text" placeholder="{{sho.username}}" name="username" id="username" >
            <label for="email"><b>Police Station Address</b></label>
            <input type="text" placeholder="{{sho.first_name}}" name="paddress" id="paddress" >
            <label for="email"><b>Police Station PINCODE</b></label>
            <input type="text" placeholder="{{sho.last_name}}" name="ppin" id="ppin" >

            <label for="psw"><b>Password</b></label>
            <input type="password" placeholder="{{sho.password}}" name="psw" id="psw" >
            
            <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>

            <button type="submit" class="registerbtn">Edit Details</button>
        </div>

        
    </form>

    <center><a  class=" mx-3 btn btn-danger " style="justify-content: center;" href="/controller/deleteSHOaccount/{{sho.username}}">Delete SHO Account</a>
    </center>
    
</div>
{% endblock body %}